apiVersion: v1
kind: Pod
metadata:
  name: net-limit-test
  namespace: ioi-system
  annotations:
    networkio.kubernetes.io/resources: |
      {
        "requests": {
          "ingress": "10M",
          "egress": "10M"
        },
        "limits": {
          "ingress": "10M",
          "egress": "10M"
        }
      }
spec:
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      limits:
        io/network.mbps: "10"
      requests:
        io/network.mbps: "10"
  restartPolicy: Never
